### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by dopeghoti** [bahamas10/hue-cli#12]
When I try to install this per the readme with `npm install hue-cli`, it fails after fetching the dependencies with the following output:

```
npm WARN enoent ENOENT: no such file or directory, open '/home/myuser/package.json'
npm WARN ghoti No description
npm WARN ghoti No repository field.
npm WARN ghoti No README data
npm WARN ghoti No license field.
```

**Comment by TwizzyDizzy** [comment]
I think this is rather a `npm` misconfiguration from my perspective. Why would `npm` search for a `package.json` in your home directory?

Could you please list the (redacted) directory of your home directory as well as the actual commands you enter?

Cheers
Thomas

**Comment by dopeghoti** [comment]
Hello,

I have since upgraded my host to Ubuntu 16.04 LTS; this includes a newer version of `node` and `npm`; the error no longer occurs.
