### ISSUE TITLE
cant execute via apache

### ISSUE THREAD

**Issue by scr44tch** [bahamas10/hue-cli#16]
When i try to run a bash script turning my light on and off via apache i get this error:

`path.js:7 throw new TypeError('Path must be a string. Received ' + inspect(path)); ^ TypeError: Path must be a string. Received undefined at assertPath (path.js:7:11) at Object.join (path.js:1211:7) at Object. (/usr/lib/node_modules/hue-cli/hue-cli.js:23:23) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.runMain (module.js:604:10) at run (bootstrap_node.js:394:7)`

it works as expected in when i call it via ssh

here is the script:

`#!/bin/bash
lights=$(hue lights 1,2,4)
if [[ $lights = *off* ]]; then
hue lights 1,2,4 on
fi
if [[ $lights = *on* ]]; then
hue lights 1,2,3,4 off
fi`

would be great if i could execute the script via the webserver,

**Comment by bahamas10** [comment]
most likely this line is causing the issue
https://github.com/bahamas10/hue-cli/blob/master/hue-cli.js#L22

try setting one of those variables in the bash script before executing the
program... like

``` bash
#!/usr/bin/env bash
export HOMEPATH=/home/user
...
```

where `/home/user` is the path that contains a `.hue.json` config file

**Comment by scr44tch** [comment]
thx for your fast answer,
script looks like this now

`#!/bin/bash
export HOMEPATH=/root
hue -H 192.168.1.55 lights off`

error: application not registered, run `hue register` first

 it wants me to register again, the .hue.json is located in /root and everything is working via normal command line

**Comment by scr44tch** [comment]
export HOMEPATH=/home/user --> thx it works now!!
