### ISSUE TITLE
3rd gen bulbs are set to wrong color

### ISSUE THREAD

**Issue by caedn** [bahamas10/hue-cli#17]
Most notably when running `hue lights all reset`, all 3rd generation (not sure about 2nd generation) lights get a noticeable green color cast. 

`white` works fine but some other predefined colors are slightly off too.

**Comment by bahamas10** [comment]
ah. i know green had issues before, i wonder if those issues have been fixed and this program doesn't account for it.  unfortunately i don't have any lights to test this.

**Comment by Spire42** [comment]
I've fixed the green color cast on reset by changing line 173 of `hue-cli.js` to:

    case 'reset': l.forEach(function(id) { client.state(id, {on: true, bri: 254, hue: 8418, sat: 140, effect: 'none', xy: [0.4573, 0.41], ct:366, alert: 'none'}, callback(id)); }); break;

I obtained these new values by physically power-cycling one of my LCT014 bulbs and then immediately dumping the state.

I've tested this with the following bulbs and they all look good:

* LWB006: White A19
* LCT007: White and Color A19 (second generation)
* LCT014: White and Color A19 (third generation, “richer colors”)
* LTW011: White Ambiance BR30

**Comment by bahamas10** [comment]
Thanks for looking up these values.  According to the API:

> There are 3 methods available to set the color of the light – hue and saturation (hs), xy or color temperature (ct). If multiple methods are used then a priority is used: xy > ct > hs. All included parameters will be updated but the ‘colormode’ will be set using the priority system.

I'm going to update this to use the `ct` parameter, as that is almost identical to the color of a 2700k (warm white) incandescent bulb, which is what I was attempting to recreate originally  - I will also make sure to clear any alerts or effects as well.
