### ISSUE TITLE
What about groups and scenes?

### ISSUE THREAD

**Issue by sinedied** [bahamas10/hue-cli#18]
Is there any plans to support group and scenes? A CLI is a great idea, but for me controlling individual light is almost useless. It seems it's supported by the API I think?

**Comment by bahamas10** [comment]
yes and yes, but not for this program.  see my comment on https://github.com/bahamas10/hue-cli/pull/10#issuecomment-269668891

I'm going to work on a new program, like `hueadm` (name pending) to manage hue 100% from the CLI

**Comment by bahamas10** [comment]
https://github.com/bahamas10/hueadm... long time coming but it's here :D

**Comment by bahamas10** [comment]
Cloning in lieu of `hueadm` linked above - hue-cli will not support groups or scenes.

**Comment by sinedied** [comment]
Just in case, in the meantime I made a simple utility to record/recall hue scenes: https://github.com/sinedied/hue-cli
