### ISSUE TITLE
Clarify what brightness values mean

### ISSUE THREAD

**Issue by malonehedges** [bahamas10/hue-cli#23]
Having +10, =100 leads me to think that its a 0-100% number when it is in reality 0-255. I think clarifying this in the help command would be helpful.

**Comment by bahamas10** [comment]
I've added documentation to show that brightness is 1-254... I've also added the ability to set it as a percentage, ie.

```
      hue lights 1 +10%           # increase the brightness by 10%
      hue lights 1 -10%           # decrease the brightness by 10%
      hue lights 1 =100%          # set the brightness to 100%
```
