### ISSUE TITLE
create own colorloop?

### ISSUE THREAD

**Issue by prankousky** [bahamas10/hue-cli#26]
hi,

is it possible to create an individual colorloop? for example, ffffff 2 seconds, blue 4 seconds, purple 6 seconds (transition time 0,3 seconds) and run it?

i was considering just writing a bash script that does this, but seems like it always takes a second for commands to be accepted by my hue bridge (or lamp), so this is not an option...

thanks in advance :)

**Comment by bahamas10** [comment]
Unfortunately, this is not possible with the HTTP interface Hue provides us.  You could write a bash script that repeatedly calls `hue-cli` to get the effect, but it will prone to the delay you are already seeing.

There is a new API that Hue has announced that looks promising https://developers.meethue.com/entertainment-blog.  That would need a separate program than `hue-cli` to work however.
