### ISSUE TITLE
Why don't use the hue.js package?

### ISSUE THREAD

**Issue by Remiii** [bahamas10/hue-cli#9]
Why do you use a tarball of `hue.js` `https://github.com/bahamas10/hue.js/tarball/dave-1432672068`? `hue.js` is avaialble with `npm` ie. `https://www.npmjs.com/package/hue.js`.

**Comment by Remiii** [comment]
Ok I found the answer: `https://github.com/thatguydan/hue.js/compare/master...bahamas10:dave-1432672068`. But it could be nice to merge this diff.

**Comment by mattbucci** [comment]
recommend issue closed
